# Generated by Django 2.2.3 on 2019-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя категории')),
                ('desc', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
    ]
